service: aws-node-apirest--students

frameworkVersion: '3'

custom:
  tableName: 'students-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  profile: serverless-admin
  environment:
    STUDENTS_TABLE: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ StudentsTable, Arn ]

functions:
  create:
    handler: students/create.create
    events:
      - httpApi:
          path: /students
          method: POST

  list:
    handler: students/list.list
    events:
      - httpApi:
          path: /students
          method: GET
          
  get:
    handler: students/get.get
    events:
      - httpApi:
          path: /students/{id}
          method: GET       

  update:
    handler: students/update.update
    events:
      - httpApi:
          path: /students/{id}
          method: PUT         

  delete:
    handler: students/delete.delete
    events:
      - httpApi:
          path: /students/{id}
          method: DELETE

resources:
  Resources:
    StudentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: studentId
            AttributeType: S
        KeySchema:
          - AttributeName: studentId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
